fir_async/urls.py
from django.conf.urls import url

from fir_async import views

urlpatterns = [
    url(r'^preferences$', views.preferences, name='preferences'),
    url(r'^preferences/(?P<method>[a-zA-Z0-9_]+)$', views.method_configuration, name='method_configuration'),
]

fir_async/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django import forms
from django.views.decorators.http import require_POST
from incidents.models import BusinessLine

import json

from fir_async.models import NotificationPreference
from fir_async.registry import registry
from fir_async.forms import NotificationPreferenceFormset


@login_required
def preferences(request):

    class NotificationPreferenceForm(forms.ModelForm):
        event = forms.ChoiceField(choices=registry.get_event_choices(), disabled=True, widget=forms.HiddenInput())
        method = forms.ChoiceField(choices=registry.get_method_choices(), disabled=True, widget=forms.HiddenInput())
        business_lines = forms.ModelMultipleChoiceField(BusinessLine.authorization.for_user(request.user,
                                                                                            'incidents.view_incidents'),
                                                        required=False)

        class Meta:
            fields = "__all__"

    formset = forms.inlineformset_factory(User, NotificationPreference,
                                          formset=NotificationPreferenceFormset,
                                          form=NotificationPreferenceForm)
    if request.method == 'POST':
        fs = formset(request.POST, instance=request.user)
        if fs.is_valid():
            fs.save()
        return redirect('user:profile')
    else:
        fs = formset(instance=request.user)

    return render(request, "fir_async/preferences.html", {'formset': fs})


@require_POST
@login_required
def method_configuration(request, method):
    method_object = registry.methods.get(method, None)
    if method is None:
        return redirect('user:profile')
    form = method_object.form(request.POST, user=request.user)
    if form.is_valid():
        form.save()
    return redirect('user:profile')

fir_async/templates/fir_async/actions.html
{% load i18n %}
{% for method, method_name in actions.items %}
<li><a href="#" id="user_configure_{{method}}" data-toggle='modal' data-target='#configure_{{method}}'><i class="glyphicon glyphicon-comment"></i>{% blocktrans %}Configure {{ method_name }}{% endblocktrans %}</a></li>
{% endfor %}

fir_async/templates/fir_async/actions_form.html
{% load i18n %}
{% load add_css_class %}

{% for method, method_form in actions.items %}
    <div id="configure_{{method}}" class="modal fade notification-method-form" tabindex="-1" role="dialog" aria-labelledby="configure-{{method}}-label" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <form id="configure_{{method}}_form" method="POST" action="{% url 'async:method_configuration' method %}">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 id="changePasswordLabel" class="modal-title">{{method_form.title}}</h4>
                    </div>
                    <div class="modal-body">
                        <div>
                            {% csrf_token %}
                            {% for field in method_form %}
                            <div class="form-group row">
                                <div class="col-sm-4">
                                    {{ field.label_tag }}
                                </div>
                                <div class="col-sm-8">
                                    {{ field|add_css_class:"form-control" }}
                                    <span class='help-block'>
                                        {% if not field.errors and field.help_text %}
                                            {{field.help_text}}
                                        {% endif %}
                                        {% for error in field.errors %}
                                            {{error}}
                                        {% endfor %}
                                    </span>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>

                    <div class="modal-footer">
                        <button class="btn btn-default" data-dismiss="modal" aria-hidden="true">{%  trans "Cancel" %}</button>
                        <button type="submit" class="btn btn-primary">{%  trans "Save" %}</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endfor %}
<script>
        window.onload = function(){console.log("TEST");
            $('.notification-method-form').on('fir.form.success', function (event) {
                console.log(this);
                $(this).modal('hide');
                event.stopPropagation();
            });
        };
    </script>

fir_async/templates/fir_async/preferences.html
{% load i18n %}
{% load add_css_class %}
{% load notifications %}
<div class="col-sm-8 col-sm-offset-2">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">{% trans "Notification preferences" %}</h3>
      </div>
      <div class="panel-body">
          <form action="{% url 'async:preferences' %}" method="post">
                {% csrf_token %}
                {{ formset.management_form }}
                {% for form in formset %}
                <div class="col-sm-3">
                    <div class="form-group">
                   <label id="id_business_lines">{{ form.get_notification_display }}</label>
                        {{ form.business_lines|add_css_class:"form-control" }}
                        {% for hidden in form.hidden_fields %}
                            {{ hidden }}
                        {% endfor %}
                    </div>
                </div>
                {% endfor %}
                <button class="btn btn-primary" type="submit">{% trans "Save" %}</button>
            </form>
      </div>
  </div>
</div>
{% notification_forms %}